extends GateBase
## Rigs of Rods' own default map loads and is drivable with nothing downloaded.
##
## Every other terrain gate in this suite skips on a fresh clone. La Paz and the hero truck are
## gitignored, because the repository's content carries varied and often unstated licensing, so a
## contributor who has just cloned this project has no world at all — and for most of this
## project's life the answer to that was a terrain generated by its own code, which is an oracle
## written by the thing it is meant to check.
##
## Rigs of Rods ships its own default map, and it is already here: `vendor/rigs-of-rods/content`
## is a pinned GPL submodule holding the map the game itself opens with. Three terrains over one
## set of files — gravel, asphalt and flooded — by tdev, Miura and CuriousMike.
##
## It exercises a path La Paz does not. `simple2.otc` states `Flat=1` and `WorldSizeY=0` and names
## a heightmap the package does not contain, because upstream never opens it: `is_flat` makes
## `TerrainGeometryManager::getHeightAt` return 0.0 before it reads anything. A reader that
## demands a heightmap rejects the map the game starts with, which is what this project's did.
##
## The claim is deliberately in two parts. What the map says about itself is checked against its
## own files and needs nothing downloaded, so it holds on any clone. The drive is added when the
## hero asset happens to be present, and skips without failing when it is not.

const SHIPPED_NAME: String = "simple2"
const MOD_DIR: String = "assets/mods/ChevyS1023"
const TRUCK: String = "S10offroad.truck"
const PRESET: String = "hero_3q"
const SUBSTEP_HZ: float = 2000.0
const SETTLE_SECONDS: float = 2.5
const DRIVE_SECONDS: float = 6.0
const THROTTLE: float = 0.7
## What `simple2.terrn2` and `simple2.otc` state about themselves. Not this project's numbers:
## they are read off the files in the submodule, and a submodule bump that changes the map is
## meant to fail here rather than pass quietly on a different terrain.
const STATED_TITLE: String = "Simple Test Terrain"
const STATED_SIZE_M: float = 1024.0
const STATED_START: Vector3 = Vector3(512.0, 0.0, 512.0)
const STATED_GRAVITY: float = -9.81
## A flat map is flat: every height Terrain3D draws is zero, to the millimetre.
const FLATNESS_TOLERANCE_M: float = 0.001
const HEIGHT_SAMPLES: int = 200
## Where the rig has to be after settling, and how far it has to get under its own power.
const MAX_SETTLE_RISE_M: float = 2.5
const MAX_SETTLE_SINK_M: float = 0.5
const MIN_DISTANCE_M: float = 20.0


static func meta() -> Dictionary:
    return {
        "name": "a_shipped_map_drives_from_a_fresh_clone",
        "proves": "Rigs of Rods' own shipped default map loads from the pinned submodule with nothing downloaded, imports flat at its stated size, and the hero truck settles and drives on it",
        "oracle": GateBase.ORACLE_EXTERNAL,
        "threshold": (
            "the map reports its own title, %.0f m extent, %v spawn and %.2f m/s^2 gravity;"
            % [STATED_SIZE_M, STATED_START, STATED_GRAVITY]
            + " Terrain3D draws it flat to %.0f mm over %d samples; the rig rests within %.1f m"
            % [FLATNESS_TOLERANCE_M * 1000.0, HEIGHT_SAMPLES, MAX_SETTLE_RISE_M]
            + " of the ground and drives at least %.0f m" % MIN_DISTANCE_M
        ),
        "why": (
            "every other terrain gate here skips on a fresh clone, because the terrains and the"
            + " hero truck are gitignored. That left a suite whose only world was one this"
            + " project generated itself, which cannot check the reader that loads somebody"
            + " else's. Upstream's own map is in the tree under GPL and it reaches a case La Paz"
            + " does not: Flat=1, no height range, and a heightmap filename the package does not"
            + " ship because the game never opens it."
        ),
        "budget_s": 180.0,
        "needs_gpu": true,
        "milestone": "M1",
    }


func run(harness: Node) -> Dictionary:
    if not ClassDB.class_exists("Terrain3D"):
        return ok("skipped: Terrain3D is not installed. Run tools/build_terrain3d.sh", 0)
    var loaded: Dictionary = RorTerrainLibrary.load_named(SHIPPED_NAME)
    if (loaded["error"] as String) != "":
        return fail(
            "%s: the vendor/rigs-of-rods content submodule is what ships it — check out with"
            % loaded["error"] + " git submodule update --init --recursive"
        )
    var terrain_data: RorTerrain = loaded["terrain"] as RorTerrain

    var stated: String = _matches_its_own_files(terrain_data)
    if stated != "":
        return fail(stated)

    var err: String = harness.setup_for(PRESET)
    if err != "":
        return fail(err)
    var terrain: Node3D = TerrainWorld.create()
    harness.world.add_child(terrain)
    await harness.advance_frames(2, "static", "terrain")
    var built: String = TerrainWorld.populate(terrain, terrain_data)
    if built != "":
        return fail(built)
    await harness.advance_frames(1, "static", "terrain")
    var data: Object = terrain.get("data")
    if data == null:
        return fail("the terrain has no data object after populating")

    var flat: Dictionary = _drawn_is_flat(data, terrain_data)
    if (flat["error"] as String) != "":
        return fail(flat["error"] as String, flat["value"] as float)

    var mod_dir: String = SourceScan.repo_root().path_join(MOD_DIR)
    if not DirAccess.dir_exists_absolute(mod_dir):
        return ok(
            "%s loads from the pinned submodule and draws flat to %.3f mm; skipped the drive:"
            % [terrain_data.name, (flat["value"] as float) * 1000.0]
            + " the hero asset is not present",
            flat["value"]
        )
    var driven: Dictionary = _drive(mod_dir, data, terrain_data)
    if (driven["error"] as String) != "":
        return fail(driven["error"] as String, driven["value"] as float)
    return ok(
        "%s from the pinned submodule: %.0f m, flat to %.3f mm, the rig settled %.2f m above it"
        % [terrain_data.name, STATED_SIZE_M, (flat["value"] as float) * 1000.0,
           driven["rest"] as float]
        + " on %s and drove %.1f m at up to %.1f m/s"
        % [driven["surface"] as String, driven["value"] as float, driven["speed"] as float],
        driven["value"]
    )


## What the map says about itself, against what its own files say. Returns "" when they agree.
func _matches_its_own_files(terrain_data: RorTerrain) -> String:
    if terrain_data.name != STATED_TITLE:
        return "the shipped map calls itself '%s' where its .terrn2 says '%s'" % [
            terrain_data.name, STATED_TITLE
        ]
    if not terrain_data.is_flat():
        return "%s does not read as flat, and its .otc states Flat=1" % terrain_data.name
    var size: float = terrain_data.geometry["world_x"] as float
    if not is_equal_approx(size, STATED_SIZE_M):
        return "the shipped map reads as %.1f m across where its .otc states %.0f" % [
            size, STATED_SIZE_M
        ]
    var start: Vector3 = terrain_data.start_position()
    if not start.is_equal_approx(STATED_START):
        return "the shipped map spawns a vehicle at %v where its .terrn2 states %v" % [
            start, STATED_START
        ]
    if not is_equal_approx(terrain_data.gravity(), STATED_GRAVITY):
        return "the shipped map asks for %.3f m/s^2 where its .terrn2 states %.2f" % [
            terrain_data.gravity(), STATED_GRAVITY
        ]
    return ""


## A flat map draws flat: every height Terrain3D reports is zero.
##
## This is the whole of the flat path's wiring in one number. A reader that fell back to reading
## the heightmap the page file names would find no file and produce zeros too, so the check is
## paired with `is_flat()` above rather than standing alone.
func _drawn_is_flat(data: Object, terrain_data: RorTerrain) -> Dictionary:
    var out: Dictionary = {"error": "", "value": 0.0}
    var grid: Dictionary = terrain_data.lattice()
    var span: float = float((grid["size"] as int) - 2) * (grid["spacing"] as float)
    var rng: RandomNumberGenerator = RandomNumberGenerator.new()
    rng.seed = HarnessCfg.SEED
    var worst: float = 0.0
    var worst_at: Vector2 = Vector2.ZERO
    for _sample: int in HEIGHT_SAMPLES:
        var at: Vector2 = Vector2(rng.randf_range(4.0, span), rng.randf_range(4.0, span))
        var theirs: float = data.call("get_height", Vector3(at.x, 0.0, at.y)) as float
        if not is_finite(theirs):
            out["error"] = (
                "Terrain3D reports no height at %v: the regions do not cover the map" % at
            )
            return out
        if absf(theirs) > worst:
            worst = absf(theirs)
            worst_at = at
    out["value"] = worst
    if worst > FLATNESS_TOLERANCE_M:
        out["error"] = (
            "the shipped map draws %.3f m from level at %v, and it states Flat=1"
            % [worst, worst_at]
        )
    return out


## Spawns the hero truck where the map says and asks it to drive.
func _drive(mod_dir: String, data: Object, terrain_data: RorTerrain) -> Dictionary:
    var out: Dictionary = {"error": "", "value": 0.0, "rest": 0.0, "speed": 0.0, "surface": ""}
    var rig: Dictionary = RigBuilder.from_file(mod_dir, TRUCK, 0.0)
    if (rig["error"] as String) != "":
        out["error"] = rig["error"] as String
        return out
    var truck: TruckParser = rig["truck"] as TruckParser
    var solver: RefCounted = rig["solver"] as RefCounted
    var applied: String = TerrainWorld.give_to_solver(solver, data)
    if applied != "":
        out["error"] = applied
        return out
    solver.set_ground(0.0, true)
    solver.set_gravity(Vector3(0.0, terrain_data.gravity(), 0.0))
    var start: Vector3 = terrain_data.start_position()
    out["surface"] = terrain_data.models.name_of(
        terrain_data.surface_at_world(start.x, start.z)
    )
    RigBuilder.place(solver, truck, Vector3(start.x, 0.0, start.z), 0.0, DriveCfg.SPAWN_HEIGHT_M)

    var dt: float = 1.0 / SUBSTEP_HZ
    var chunk: int = int(SUBSTEP_HZ / 60.0)
    for _frame: int in int(SETTLE_SECONDS * 60.0):
        solver.step(dt, chunk)
    var settled: Vector3 = ActorFrame.of(solver.get_positions(), truck.camera_nodes).origin
    if not is_finite(settled.length()):
        out["error"] = "the solver went non-finite while the rig settled"
        return out
    var ground: float = terrain_data.height_at_world(settled.x, settled.z)
    out["rest"] = settled.y - ground
    if settled.y - ground > MAX_SETTLE_RISE_M:
        out["error"] = (
            "the rig settled %.2f m above the ground at %v: the heightfield and the drawn map"
            % [settled.y - ground, settled] + " are not the same surface"
        )
        return out
    if ground - settled.y > MAX_SETTLE_SINK_M:
        out["error"] = (
            "the rig sank %.2f m into the ground at %v: it is falling through the map"
            % [ground - settled.y, settled]
        )
        return out

    solver.start_engine()
    solver.set_gear_selector(1)
    solver.set_throttle(THROTTLE)
    var fastest: float = 0.0
    for frame: int in int(DRIVE_SECONDS * 60.0):
        solver.step(dt, chunk)
        fastest = maxf(fastest, absf(solver.road_speed()))
        if not is_finite(solver.get_node_position(0).length()):
            out["error"] = "the solver went non-finite %.2f s into the drive" % (
                float(frame) / 60.0)
            return out
    var finished: Vector3 = ActorFrame.of(solver.get_positions(), truck.camera_nodes).origin
    var travelled: float = Vector2(finished.x - settled.x, finished.z - settled.z).length()
    out["value"] = travelled
    out["speed"] = fastest
    if travelled < MIN_DISTANCE_M:
        out["error"] = (
            "%.1f s of throttle moved the rig %.1f m across the map, under %.0f: it is not"
            % [DRIVE_SECONDS, travelled, MIN_DISTANCE_M] + " driving on this ground"
        )
    return out
