class_name RorTerrain
extends RefCounted
## A Rigs of Rods terrain, loaded from the files its author shipped.
##
## Everything this project has stood on so far was generated by a function: Valley One and the test
## park are code, which makes them reproducible and makes their gates cheap. A real terrain is the
## other thing — 8 MB of 16-bit samples, a traction map painted in an image editor, friction
## numbers in the terrain's own config — and the point of loading one is that it was built and
## driven by people against those numbers, so it is an oracle the project cannot write for itself.
##
## This is the same shape interface `ValleyShape` and `ParkShape` present — a height and a surface
## per lattice cell, a tint per world position — so the terrain builder, the collision bridge and
## the gates take it without knowing which they have. The difference is that it is an instance
## rather than a script, because it holds the files.
##
## Two numbers decide whether it is the terrain its author drew:
##
##   - a height is `sample / 65535 * WorldSizeY`, so La Paz's 35 m of range is the whole of it;
##   - the lattice is `PageSize - 1` cells of `WorldSizeX / (PageSize - 1)` metres, which for a
##     2049-sample page across 4000 m is 2048 cells of 1.953125 m.
##
## The last sample row and column are dropped, because Terrain3D's regions tile on a power of two
## and 2049 does not: the terrain is 3998.05 m of a 4000 m map, its far edge two metres short.
## Nothing is resampled to achieve that — a resampled heightmap is no longer the author's.

## Where a terrain's own textures say the ground is, when it paints nothing over the base layer.
const DEFAULT_TINT: Color = Color(0.5, 0.45, 0.4)
## How dark the tint may go. The splat textures' averages are all mid-tones, and a colour map is
## the only albedo this project has proven reaches the screen, so a black tint is a bug.
const MIN_TINT_LUMA: float = 0.05

var directory: String = ""
var name: String = ""
var config: Dictionary = {}
var geometry: Dictionary = {}
var page: Dictionary = {}
var traction: Dictionary = {}
var models: GroundModelSet = null

var _heights: PackedByteArray = PackedByteArray()
var _samples: int = 0
var _height_scale: float = 0.0
var _traction_image: Image = null
var _blend_image: Image = null
## One average colour per splat layer, and which channel of the blend map selects it.
var _layer_tints: Array[Color] = []
var _layer_channels: PackedStringArray = PackedStringArray()
var _layer_alphas: PackedFloat32Array = PackedFloat32Array()
## Surface name -> index in `models`, so a per-cell lookup is not a string search.
var _surface_indices: Dictionary = {}
var _default_surface: int = 0


## Loads the terrain in a directory. Returns null and leaves `error` set on the result of
## `last_error()` when it cannot be read.
static func load_from(directory_path: String) -> Dictionary:
    var out: Dictionary = {"error": "", "terrain": null}
    var terrn2_path: String = _find(directory_path, "terrn2")
    if terrn2_path.is_empty():
        out["error"] = "no .terrn2 in %s" % directory_path
        return out
    var terrain: RorTerrain = RorTerrain.new()
    terrain.directory = directory_path
    out["error"] = terrain._read(terrn2_path)
    if (out["error"] as String) != "":
        return out
    out["terrain"] = terrain
    return out


## The lattice the terrain is sampled on: how many cells across, how many metres apart, and where
## its first cell is in the world. The shape interface's own question, asked of a real terrain.
func lattice() -> Dictionary:
    return {
        "size": _samples - 1,
        "spacing": (geometry["world_x"] as float) / float(_samples - 1),
        "origin": Vector3.ZERO,
    }


## Where a lattice cell is in the world. RoR terrains start at the origin and run positive.
func world_of(x_index: int, z_index: int) -> Vector2:
    var spacing: float = lattice()["spacing"] as float
    return Vector2(float(x_index) * spacing, float(z_index) * spacing)


## The terrain's height at a lattice cell, in metres.
func height_at(x_index: int, z_index: int) -> float:
    return _sample(x_index, z_index)


## The terrain's height at a world position, interpolated between samples the way a wheel meets it.
func height_at_world(x: float, z: float) -> float:
    var spacing: float = lattice()["spacing"] as float
    var fx: float = x / spacing
    var fz: float = z / spacing
    var x0: int = int(floor(fx))
    var z0: int = int(floor(fz))
    var tx: float = fx - float(x0)
    var tz: float = fz - float(z0)
    var north: float = lerpf(_sample(x0, z0), _sample(x0 + 1, z0), tx)
    var south: float = lerpf(_sample(x0, z0 + 1), _sample(x0 + 1, z0 + 1), tx)
    return lerpf(north, south, tz)


## Which surface a lattice cell is, as an index into `models`.
func surface_at(x_index: int, z_index: int) -> int:
    var world: Vector2 = world_of(x_index, z_index)
    return surface_at_world(world.x, world.y)


## Which surface a world position is. The traction map is the terrain's own painted image, and a
## colour it does not name is the landuse config's own default.
func surface_at_world(x: float, z: float) -> int:
    if _traction_image == null:
        return _default_surface
    var pixel: Color = _traction_image.get_pixelv(_image_cell(_traction_image, x, z))
    var surface: String = Landuse.surface_of(traction, pixel)
    return _surface_indices.get(surface, _default_surface) as int


## What colour the ground is at a world position.
##
## The terrain's own look is four tiled textures blended by a splat map, and this is the honest
## part of that a colour map can hold: each layer's average colour, composited in the order the
## page file lists them, at the weights the splat map paints. Tiling detail needs the textures
## themselves on the terrain material, which is a separate piece of work.
func tint_at(x: float, z: float) -> Color:
    if _layer_tints.is_empty():
        return DEFAULT_TINT
    var out: Color = _layer_tints[0]
    if _blend_image == null:
        return out
    var blend: Color = _blend_image.get_pixelv(_image_cell(_blend_image, x, z))
    for index: int in range(1, _layer_tints.size()):
        var weight: float = _channel(blend, _layer_channels[index]) * _layer_alphas[index]
        out = out.lerp(_layer_tints[index], clampf(weight, 0.0, 1.0))
    return out


## Where a vehicle starts, as the terrain's own config states it.
func start_position() -> Vector3:
    return config["start_position"] as Vector3


## What gravity the terrain asks for, in m/s^2.
func gravity() -> float:
    return config["gravity"] as float


## A name for this terrain's cache directory, and a salt that changes when its files do.
func cache_name() -> String:
    return "ror_%s" % directory.get_file().to_lower()


func cache_salt() -> String:
    return "%s:%d:%d" % [name, _heights.size(), _samples]


## --- Loading --------------------------------------------------------------------------------


func _read(terrn2_path: String) -> String:
    config = Terrn2.read(terrn2_path)
    if (config["error"] as String) != "":
        return config["error"] as String
    name = config["name"] as String
    geometry = Otc.read(directory.path_join(config["geometry_config"] as String))
    if (geometry["error"] as String) != "":
        return geometry["error"] as String
    page = Otc.read_page(directory.path_join(geometry["page_file"] as String))
    if (page["error"] as String) != "":
        return page["error"] as String
    var heightmap: String = directory.path_join(page["heightmap"] as String)
    _heights = FileAccess.get_file_as_bytes(heightmap)
    _samples = geometry["samples"] as int
    var wanted: int = _samples * _samples * (geometry["bytes_per_sample"] as int)
    if _heights.size() < wanted:
        return "%s holds %d bytes where %d samples of %d bytes need %d" % [
            page["heightmap"], _heights.size(), _samples * _samples,
            geometry["bytes_per_sample"], wanted
        ]
    _height_scale = (geometry["world_y"] as float) / 65535.0
    var surfaces: String = _read_surfaces()
    if surfaces != "":
        return surfaces
    _read_layers()
    return ""


## The traction map and the friction numbers behind it.
func _read_surfaces() -> String:
    models = GroundModelSet.upstream()
    var landuse_file: String = config["traction_map"] as String
    if landuse_file.is_empty():
        return ""
    traction = Landuse.read(directory.path_join(landuse_file))
    if (traction["error"] as String) != "":
        return traction["error"] as String
    for cfg: String in traction["ground_model_configs"] as PackedStringArray:
        models.add_config(directory.path_join(cfg))
    _traction_image = Image.load_from_file(directory.path_join(traction["texture"] as String))
    if _traction_image == null:
        return "the traction map image %s could not be read" % traction["texture"]
    for index: int in models.size():
        _surface_indices[models.name_of(index)] = index
    var fallback: String = traction["default_use"] as String
    _default_surface = maxi(models.index_of(fallback), 0)
    return ""


## The splat layers: each one's average colour, and which channel paints it.
func _read_layers() -> void:
    for layer: Dictionary in page["layers"] as Array[Dictionary]:
        _layer_tints.append(_average(layer["albedo"] as String))
        _layer_channels.append(layer["channel"] as String)
        _layer_alphas.append(layer["alpha"] as float)
        var blend_file: String = layer["blend_map"] as String
        if _blend_image == null and not blend_file.is_empty():
            _blend_image = Image.load_from_file(directory.path_join(blend_file))


## One texture's average colour. Its own pixels: a terrain's palette is in its textures, and
## picking colours by eye here would be this project inventing the look of someone else's map.
func _average(texture: String) -> Color:
    if texture.is_empty():
        return DEFAULT_TINT
    var path: String = directory.path_join(texture)
    var image: Image = Dds.load_image(path) if path.get_extension().to_lower() == "dds" else (
        Image.load_from_file(path)
    )
    if image == null:
        return DEFAULT_TINT
    if image.is_compressed():
        if image.decompress() != OK:
            return DEFAULT_TINT
    image.resize(1, 1, Image.INTERPOLATE_LANCZOS)
    var out: Color = image.get_pixel(0, 0)
    # These textures carry a spec or height channel in their alpha, and it is often zero. The
    # colour is what is wanted, at full opacity.
    out.a = 1.0
    if out.get_luminance() < MIN_TINT_LUMA:
        return DEFAULT_TINT
    return out


## --- Sampling -------------------------------------------------------------------------------


## One raw sample, clamped to the map. Row-major from the origin, which is what the file is:
## measured against the terrain's own StartPosition, its height there is 7.377 m where the config
## says a vehicle starts at 7.375.
func _sample(x_index: int, z_index: int) -> float:
    var x: int = clampi(x_index, 0, _samples - 1)
    var z: int = clampi(z_index, 0, _samples - 1)
    if geometry["flip_x"] as bool:
        x = _samples - 1 - x
    return float(_heights.decode_u16((z * _samples + x) * 2)) * _height_scale


## Which pixel of one of the terrain's images covers a world position.
func _image_cell(image: Image, x: float, z: float) -> Vector2i:
    var across: float = x / (geometry["world_x"] as float)
    var along: float = z / (geometry["world_z"] as float)
    return Vector2i(
        clampi(int(across * float(image.get_width())), 0, image.get_width() - 1),
        clampi(int(along * float(image.get_height())), 0, image.get_height() - 1)
    )


func _channel(colour: Color, channel: String) -> float:
    match channel:
        "R":
            return colour.r
        "G":
            return colour.g
        "B":
            return colour.b
        "A":
            return colour.a
    return 0.0


static func _find(directory_path: String, extension: String) -> String:
    var found: PackedStringArray = PackedStringArray()
    for file: String in DirAccess.get_files_at(directory_path):
        if file.get_extension().to_lower() == extension:
            found.append(file)
    if found.is_empty():
        return ""
    found.sort()
    return directory_path.path_join(found[0])
