extends GateBase
## A Rigs of Rods terrain loads as the terrain its author shipped: the height where its own config
## says a vehicle starts, the surfaces its traction map paints, and the friction its own ground
## model config states.
##
## This is the first content in the project that nobody here wrote. Valley One and the test park are
## functions, and a function's gate can only ever check this project against itself. A real terrain
## arrives with numbers from outside — 2049 samples across 4000 m, 35 m of height range, a start
## position its author drove from, friction coefficients that differ from upstream's on purpose —
## and each of those is an oracle.
##
## The strongest of them is the start position. `lapaz.terrn2` states where a vehicle spawns,
## including its height, and that height is only reproduced if the raw heightmap is decoded with
## the right word size, the right row order, the right vertical scale and the right cell spacing.
## Get any one of them wrong and the terrain still loads, still looks like terrain, and is the
## wrong shape: 4.4 m out with the rows flipped, 33 m out with the bytes swapped.

const TERRAIN_DIR: String = "assets/terrains/lapaz2"
## What the author's own start position has to agree with, in metres. A spawn point is stated to
## the millimetre and sits just above the ground, so this is tight on purpose.
const START_TOLERANCE_M: float = 0.10
## How much of the map to walk when checking a vehicle would meet more than one surface.
const TRACTION_SAMPLES: int = 64
## And how coarsely the traction image itself is read. Every fourth pixel of a 1024 image is a
## sample every 15.6 m, which is finer than anything painted in one.
const TRACTION_STRIDE_PX: int = 4
## The most of the map one surface may cover before the traction map is not being read at all.
const MAX_SINGLE_SURFACE_SHARE: float = 0.95
## How much the tint has to vary across the map.
const MIN_TINT_RANGE: float = 0.02
## The surface whose friction is checked against the terrain's own config, and where that config
## states it. La Paz overrides upstream's sand: 0.5 static where upstream has 0.7.
const OVERRIDDEN_SURFACE: String = "sand"


static func meta() -> Dictionary:
    return {
        "name": "ror_terrain_matches_its_files",
        "proves": "a real Rigs of Rods terrain loads at the scale, height and orientation its own configs state, with the surfaces its traction map paints and the friction its own ground model config overrides",
        # the format readers first, then the terrain they read.
        "builds_on": ["ground_models_match_upstream"],
        "oracle": GateBase.ORACLE_EXTERNAL,
        "threshold": (
            "ground within %.2f m of the terrain's own StartPosition, every surface its landuse"
            % START_TOLERANCE_M
            + " config names present, no surface over %.0f%% of the map, and the overridden"
            % (MAX_SINGLE_SURFACE_SHARE * 100.0)
            + " friction equal to the terrain's own config"
        ),
        "why": (
            "everything driven on so far was generated by this project, so its gates could only"
            + " check this project against itself. A shipped terrain brings numbers from outside:"
            + " its start position reproduces only if the heightmap's word size, row order,"
            + " vertical scale and cell spacing are all right, and a wrong one of those loads a"
            + " terrain that looks like terrain and is the wrong shape."
        ),
        "budget_s": 60.0,
        "needs_gpu": false,
        "milestone": "M1",
    }


func run(_harness: Node) -> Dictionary:
    var directory: String = SourceScan.repo_root().path_join(TERRAIN_DIR)
    if not DirAccess.dir_exists_absolute(directory):
        return ok("skipped: no terrain at %s" % TERRAIN_DIR, 0)
    var loaded: Dictionary = RorTerrain.load_from(directory)
    if (loaded["error"] as String) != "":
        return fail(loaded["error"] as String)
    var terrain: RorTerrain = loaded["terrain"] as RorTerrain

    var geometry: String = _geometry_agrees(terrain)
    if geometry != "":
        return fail(geometry)

    # The author's own start position, which is the whole of the decode checked at once.
    var start: Vector3 = terrain.start_position()
    var ground: float = terrain.height_at_world(start.x, start.z)
    var off: float = absf(start.y - ground)
    if off > START_TOLERANCE_M:
        return fail(
            "%s spawns a vehicle at %.3f m above (%.1f, %.1f) and the heightmap there is %.3f m,"
            % [terrain.name, start.y, start.x, start.z, ground]
            + " %.3f m out: the heightmap is not being decoded as its author wrote it" % off,
            off
        )

    var painted: Dictionary = _traction_is_painted(terrain)
    if (painted["error"] as String) != "":
        return fail(painted["error"] as String, painted["value"] as float)
    var friction: String = _friction_is_the_terrains(terrain, directory)
    if friction != "":
        return fail(friction)
    var tint: Dictionary = _tint_varies(terrain)
    if (tint["error"] as String) != "":
        return fail(tint["error"] as String, tint["value"] as float)

    var lattice: Dictionary = terrain.lattice()
    return ok(
        "%s: %d cells of %.4f m, ground %.3f m under a spawn stated at %.3f m, %s, tint over"
        % [terrain.name, lattice["size"], lattice["spacing"], ground, start.y,
           painted["detail"] as String]
        + " %.3f of luma" % (tint["value"] as float),
        off
    )


## The configs agree with the files they describe: the heightmap is exactly as many samples as the
## geometry config claims, and the page file names the heightmap the terrain actually ships.
func _geometry_agrees(terrain: RorTerrain) -> String:
    var samples: int = terrain.geometry["samples"] as int
    var per_sample: int = terrain.geometry["bytes_per_sample"] as int
    var heightmap: String = terrain.directory.path_join(terrain.page["heightmap"] as String)
    var size: int = FileAccess.get_file_as_bytes(heightmap).size()
    var wanted: int = samples * samples * per_sample
    if size != wanted:
        return (
            "%s is %d bytes where %s states %d samples of %d bytes (%d)"
            % [terrain.page["heightmap"], size, terrain.config["geometry_config"],
               samples * samples, per_sample, wanted]
        )
    var world_y: float = terrain.geometry["world_y"] as float
    var highest: float = 0.0
    var lowest: float = world_y
    var lattice: Dictionary = terrain.lattice()
    var stride: int = maxi((lattice["size"] as int) / 256, 1)
    for z: int in range(0, lattice["size"] as int, stride):
        for x: int in range(0, lattice["size"] as int, stride):
            var height: float = terrain.height_at(x, z)
            highest = maxf(highest, height)
            lowest = minf(lowest, height)
    if highest > world_y + 0.001:
        return "the heightmap reaches %.2f m where WorldSizeY is %.2f" % [highest, world_y]
    # A map whose samples never leave the bottom of their range is a map being read as the wrong
    # word size: half of every 16-bit sample is a small number.
    if highest < world_y * 0.25:
        return (
            "the heightmap's highest point is %.2f m of a stated %.2f m range: the samples are"
            % [highest, world_y] + " not being read as the author's"
        )
    return ""


## The traction map is read, every colour it actually carries means a surface with friction, and
## more than one surface comes out of it.
##
## A colour the landuse config names and the image never uses is not a fault: what a painter
## painted is the painter's business, and La Paz names an asphalt red its roads barely use. What
## would be a fault is a colour in the image that resolves to nothing, or a map that comes out as
## one surface everywhere — which is what a traction map being ignored looks like.
func _traction_is_painted(terrain: RorTerrain) -> Dictionary:
    var out: Dictionary = {"error": "", "value": 0.0, "detail": ""}
    var named: Dictionary = terrain.traction["surfaces"] as Dictionary
    var every: Dictionary = {terrain.traction["default_use"] as String: true}
    for key: int in named.keys():
        every[named[key] as String] = true
    for surface: String in every.keys():
        if terrain.models.index_of(surface) < 0:
            out["error"] = (
                "the traction map names '%s' and the terrain's ground models do not describe it:"
                % surface + " a surface with no friction is a surface a wheel falls through"
            )
            return out

    # The image itself, so a colour that is painted and means nothing is caught wherever it is.
    var image: Image = Image.load_from_file(
        terrain.directory.path_join(terrain.traction["texture"] as String)
    )
    if image == null:
        out["error"] = "the traction map image %s could not be read" % terrain.traction["texture"]
        return out
    var counts: Dictionary = {}
    var counted: int = 0
    for y: int in range(0, image.get_height(), TRACTION_STRIDE_PX):
        for x: int in range(0, image.get_width(), TRACTION_STRIDE_PX):
            var pixel: Color = image.get_pixel(x, y)
            var surface: String = Landuse.surface_of(terrain.traction, pixel)
            if terrain.models.index_of(surface) < 0:
                out["error"] = (
                    "the traction map paints 0x%06x at (%d, %d), which no ground model describes"
                    % [Landuse.pixel_key(pixel), x, y]
                )
                return out
            counts[surface] = (counts.get(surface, 0) as int) + 1
            counted += 1
    var most: int = 0
    var most_named: String = ""
    var present: PackedStringArray = PackedStringArray()
    for surface: String in counts.keys():
        var share: int = counts[surface] as int
        present.append("%s %.1f%%" % [surface, float(share) * 100.0 / float(counted)])
        if share > most:
            most = share
            most_named = surface
    var share_of_map: float = float(most) / float(maxi(counted, 1))
    out["value"] = share_of_map
    if counts.size() < 2:
        out["error"] = (
            "every one of %d pixels of the traction map is '%s': its colours are not reaching its"
            % [counted, most_named] + " surfaces"
        )
        return out
    if share_of_map > MAX_SINGLE_SURFACE_SHARE:
        out["error"] = (
            "'%s' covers %.1f%% of the traction map: its colours are barely reaching its surfaces"
            % [most_named, share_of_map * 100.0]
        )
        return out
    # And the same colours have to survive the path a wheel takes: image pixel to world position
    # to ground model index, which is a different function from the one just walked.
    var span_x: float = terrain.geometry["world_x"] as float
    var span_z: float = terrain.geometry["world_z"] as float
    var driven: Dictionary = {}
    for iz: int in TRACTION_SAMPLES:
        for ix: int in TRACTION_SAMPLES:
            var surface: String = terrain.models.name_of(terrain.surface_at_world(
                span_x * (float(ix) + 0.5) / float(TRACTION_SAMPLES),
                span_z * (float(iz) + 0.5) / float(TRACTION_SAMPLES)
            ))
            driven[surface] = true
    if driven.size() < 2:
        out["error"] = (
            "the traction map carries %d surfaces and a vehicle driving the map would meet %d:"
            % [counts.size(), driven.size()] + " the world-to-pixel mapping is wrong"
        )
        return out
    out["detail"] = "surfaces " + ", ".join(present)
    return out


## The friction that reaches the set is the terrain's own, not upstream's.
##
## Read straight out of the terrain's config here, by looking for the line rather than by using
## this project's parser: a parser checked against itself proves nothing about whether the numbers
## a wheel gets are the ones the author wrote.
func _friction_is_the_terrains(terrain: RorTerrain, directory: String) -> String:
    var configs: PackedStringArray = terrain.traction["ground_model_configs"] as PackedStringArray
    if configs.is_empty():
        return ""
    var text: String = RorText.read(directory.path_join(configs[0]))
    var stated: float = _stated(text, OVERRIDDEN_SURFACE, "static friction coefficient")
    if stated <= 0.0:
        return "%s states no static friction for '%s'" % [configs[0], OVERRIDDEN_SURFACE]
    var values: Array = terrain.models.values_of(OVERRIDDEN_SURFACE)
    if values.is_empty():
        return "the terrain's ground models do not hold '%s'" % OVERRIDDEN_SURFACE
    if not is_equal_approx(float(values[1]), stated):
        return (
            "'%s' reaches the solver with %.3f of static friction where %s states %.3f"
            % [OVERRIDDEN_SURFACE, float(values[1]), configs[0], stated]
        )
    var upstream: Array = GroundModels.SURFACES.get(OVERRIDDEN_SURFACE, []) as Array
    if not upstream.is_empty() and is_equal_approx(float(upstream[1]), stated):
        return (
            "'%s' is stated as %.3f by both the terrain and upstream, so this proves nothing about"
            % [OVERRIDDEN_SURFACE, stated] + " which one reached the solver"
        )
    return ""


## One value from a ground model config, found by reading its lines.
func _stated(text: String, section: String, key: String) -> float:
    var inside: bool = false
    for raw_line: String in text.split("\n"):
        var line: String = raw_line.strip_edges()
        if line.begins_with("["):
            inside = line.to_lower() == "[%s]" % section
            continue
        if not inside or not line.contains("="):
            continue
        if line.get_slice("=", 0).strip_edges().to_lower() == key:
            return line.get_slice("=", 1).strip_edges().to_float()
    return 0.0


## The colour map the terrain will be painted with carries the map's own variety.
func _tint_varies(terrain: RorTerrain) -> Dictionary:
    var span_x: float = terrain.geometry["world_x"] as float
    var span_z: float = terrain.geometry["world_z"] as float
    var lowest: float = INF
    var highest: float = -INF
    for iz: int in TRACTION_SAMPLES:
        for ix: int in TRACTION_SAMPLES:
            var tint: Color = terrain.tint_at(
                span_x * (float(ix) + 0.5) / float(TRACTION_SAMPLES),
                span_z * (float(iz) + 0.5) / float(TRACTION_SAMPLES)
            )
            var luma: float = tint.get_luminance()
            lowest = minf(lowest, luma)
            highest = maxf(highest, luma)
    var range_of: float = highest - lowest
    if lowest < RorTerrain.MIN_TINT_LUMA:
        return {
            "error": "the terrain's tint reaches %.3f luma: its textures are not being read" % lowest,
            "value": lowest,
        }
    if range_of < MIN_TINT_RANGE:
        return {
            "error": (
                "the terrain's tint varies by %.4f across the whole map: the splat map is not"
                % range_of + " reaching the colour"
            ),
            "value": range_of,
        }
    return {"error": "", "value": range_of}
